// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/message.proto

package com.thoughtworks.message;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code message.DataType}
   */
  public enum DataType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TRADE_DATA = 0;</code>
     */
    TRADE_DATA(0),
    /**
     * <code>MARKET_DATA = 1;</code>
     */
    MARKET_DATA(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TRADE_DATA = 0;</code>
     */
    public static final int TRADE_DATA_VALUE = 0;
    /**
     * <code>MARKET_DATA = 1;</code>
     */
    public static final int MARKET_DATA_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataType valueOf(int value) {
      return forNumber(value);
    }

    public static DataType forNumber(int value) {
      switch (value) {
        case 0: return TRADE_DATA;
        case 1: return MARKET_DATA;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
            public DataType findValueByNumber(int number) {
              return DataType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.thoughtworks.message.MessageProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final DataType[] VALUES = values();

    public static DataType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:message.DataType)
  }

  public interface MsgIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.MsgId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ReqId = 1;</code>
     */
    java.lang.String getReqId();
    /**
     * <code>string ReqId = 1;</code>
     */
    com.google.protobuf.ByteString
        getReqIdBytes();

    /**
     * <code>string FOId = 2;</code>
     */
    java.lang.String getFOId();
    /**
     * <code>string FOId = 2;</code>
     */
    com.google.protobuf.ByteString
        getFOIdBytes();
  }
  /**
   * Protobuf type {@code message.MsgId}
   */
  public  static final class MsgId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.MsgId)
      MsgIdOrBuilder {
    // Use MsgId.newBuilder() to construct.
    private MsgId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgId() {
      reqId_ = "";
      fOId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MsgId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              reqId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fOId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thoughtworks.message.MessageProtos.internal_static_message_MsgId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thoughtworks.message.MessageProtos.internal_static_message_MsgId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thoughtworks.message.MessageProtos.MsgId.class, com.thoughtworks.message.MessageProtos.MsgId.Builder.class);
    }

    public static final int REQID_FIELD_NUMBER = 1;
    private volatile java.lang.Object reqId_;
    /**
     * <code>string ReqId = 1;</code>
     */
    public java.lang.String getReqId() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reqId_ = s;
        return s;
      }
    }
    /**
     * <code>string ReqId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReqIdBytes() {
      java.lang.Object ref = reqId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reqId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FOID_FIELD_NUMBER = 2;
    private volatile java.lang.Object fOId_;
    /**
     * <code>string FOId = 2;</code>
     */
    public java.lang.String getFOId() {
      java.lang.Object ref = fOId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fOId_ = s;
        return s;
      }
    }
    /**
     * <code>string FOId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFOIdBytes() {
      java.lang.Object ref = fOId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fOId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReqIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqId_);
      }
      if (!getFOIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fOId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqId_);
      }
      if (!getFOIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fOId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thoughtworks.message.MessageProtos.MsgId)) {
        return super.equals(obj);
      }
      com.thoughtworks.message.MessageProtos.MsgId other = (com.thoughtworks.message.MessageProtos.MsgId) obj;

      boolean result = true;
      result = result && getReqId()
          .equals(other.getReqId());
      result = result && getFOId()
          .equals(other.getFOId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId().hashCode();
      hash = (37 * hash) + FOID_FIELD_NUMBER;
      hash = (53 * hash) + getFOId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.MsgId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thoughtworks.message.MessageProtos.MsgId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.MsgId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.MsgId)
        com.thoughtworks.message.MessageProtos.MsgIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_MsgId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_MsgId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thoughtworks.message.MessageProtos.MsgId.class, com.thoughtworks.message.MessageProtos.MsgId.Builder.class);
      }

      // Construct using com.thoughtworks.message.MessageProtos.MsgId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        reqId_ = "";

        fOId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_MsgId_descriptor;
      }

      public com.thoughtworks.message.MessageProtos.MsgId getDefaultInstanceForType() {
        return com.thoughtworks.message.MessageProtos.MsgId.getDefaultInstance();
      }

      public com.thoughtworks.message.MessageProtos.MsgId build() {
        com.thoughtworks.message.MessageProtos.MsgId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.thoughtworks.message.MessageProtos.MsgId buildPartial() {
        com.thoughtworks.message.MessageProtos.MsgId result = new com.thoughtworks.message.MessageProtos.MsgId(this);
        result.reqId_ = reqId_;
        result.fOId_ = fOId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thoughtworks.message.MessageProtos.MsgId) {
          return mergeFrom((com.thoughtworks.message.MessageProtos.MsgId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thoughtworks.message.MessageProtos.MsgId other) {
        if (other == com.thoughtworks.message.MessageProtos.MsgId.getDefaultInstance()) return this;
        if (!other.getReqId().isEmpty()) {
          reqId_ = other.reqId_;
          onChanged();
        }
        if (!other.getFOId().isEmpty()) {
          fOId_ = other.fOId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thoughtworks.message.MessageProtos.MsgId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thoughtworks.message.MessageProtos.MsgId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object reqId_ = "";
      /**
       * <code>string ReqId = 1;</code>
       */
      public java.lang.String getReqId() {
        java.lang.Object ref = reqId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reqId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ReqId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReqIdBytes() {
        java.lang.Object ref = reqId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reqId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ReqId = 1;</code>
       */
      public Builder setReqId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ReqId = 1;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = getDefaultInstance().getReqId();
        onChanged();
        return this;
      }
      /**
       * <code>string ReqId = 1;</code>
       */
      public Builder setReqIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reqId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fOId_ = "";
      /**
       * <code>string FOId = 2;</code>
       */
      public java.lang.String getFOId() {
        java.lang.Object ref = fOId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fOId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FOId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFOIdBytes() {
        java.lang.Object ref = fOId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fOId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FOId = 2;</code>
       */
      public Builder setFOId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fOId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FOId = 2;</code>
       */
      public Builder clearFOId() {
        
        fOId_ = getDefaultInstance().getFOId();
        onChanged();
        return this;
      }
      /**
       * <code>string FOId = 2;</code>
       */
      public Builder setFOIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fOId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:message.MsgId)
    }

    // @@protoc_insertion_point(class_scope:message.MsgId)
    private static final com.thoughtworks.message.MessageProtos.MsgId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thoughtworks.message.MessageProtos.MsgId();
    }

    public static com.thoughtworks.message.MessageProtos.MsgId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgId>
        PARSER = new com.google.protobuf.AbstractParser<MsgId>() {
      public MsgId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgId> getParserForType() {
      return PARSER;
    }

    public com.thoughtworks.message.MessageProtos.MsgId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CtrlMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.CtrlMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string FOName = 1;</code>
     */
    java.lang.String getFOName();
    /**
     * <code>string FOName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFONameBytes();

    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */
    int getStatisticsCount();
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */
    boolean containsStatistics(
        java.lang.String key);
    /**
     * Use {@link #getStatisticsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getStatistics();
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getStatisticsMap();
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */

    int getStatisticsOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */

    int getStatisticsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code message.CtrlMsg}
   */
  public  static final class CtrlMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.CtrlMsg)
      CtrlMsgOrBuilder {
    // Use CtrlMsg.newBuilder() to construct.
    private CtrlMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CtrlMsg() {
      fOName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CtrlMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              fOName_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                statistics_ = com.google.protobuf.MapField.newMapField(
                    StatisticsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              statistics__ = input.readMessage(
                  StatisticsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              statistics_.getMutableMap().put(
                  statistics__.getKey(), statistics__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thoughtworks.message.MessageProtos.internal_static_message_CtrlMsg_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetStatistics();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thoughtworks.message.MessageProtos.internal_static_message_CtrlMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thoughtworks.message.MessageProtos.CtrlMsg.class, com.thoughtworks.message.MessageProtos.CtrlMsg.Builder.class);
    }

    private int bitField0_;
    public static final int FONAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object fOName_;
    /**
     * <code>string FOName = 1;</code>
     */
    public java.lang.String getFOName() {
      java.lang.Object ref = fOName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fOName_ = s;
        return s;
      }
    }
    /**
     * <code>string FOName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFONameBytes() {
      java.lang.Object ref = fOName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fOName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATISTICS_FIELD_NUMBER = 2;
    private static final class StatisticsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.thoughtworks.message.MessageProtos.internal_static_message_CtrlMsg_StatisticsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> statistics_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetStatistics() {
      if (statistics_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatisticsDefaultEntryHolder.defaultEntry);
      }
      return statistics_;
    }

    public int getStatisticsCount() {
      return internalGetStatistics().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */

    public boolean containsStatistics(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetStatistics().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatisticsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getStatistics() {
      return getStatisticsMap();
    }
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getStatisticsMap() {
      return internalGetStatistics().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */

    public int getStatisticsOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStatistics().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; Statistics = 2;</code>
     */

    public int getStatisticsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStatistics().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFONameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fOName_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStatistics(),
          StatisticsDefaultEntryHolder.defaultEntry,
          2);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFONameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fOName_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetStatistics().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        statistics__ = StatisticsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, statistics__);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thoughtworks.message.MessageProtos.CtrlMsg)) {
        return super.equals(obj);
      }
      com.thoughtworks.message.MessageProtos.CtrlMsg other = (com.thoughtworks.message.MessageProtos.CtrlMsg) obj;

      boolean result = true;
      result = result && getFOName()
          .equals(other.getFOName());
      result = result && internalGetStatistics().equals(
          other.internalGetStatistics());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FONAME_FIELD_NUMBER;
      hash = (53 * hash) + getFOName().hashCode();
      if (!internalGetStatistics().getMap().isEmpty()) {
        hash = (37 * hash) + STATISTICS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStatistics().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.CtrlMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thoughtworks.message.MessageProtos.CtrlMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.CtrlMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.CtrlMsg)
        com.thoughtworks.message.MessageProtos.CtrlMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_CtrlMsg_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetStatistics();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableStatistics();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_CtrlMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thoughtworks.message.MessageProtos.CtrlMsg.class, com.thoughtworks.message.MessageProtos.CtrlMsg.Builder.class);
      }

      // Construct using com.thoughtworks.message.MessageProtos.CtrlMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fOName_ = "";

        internalGetMutableStatistics().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_CtrlMsg_descriptor;
      }

      public com.thoughtworks.message.MessageProtos.CtrlMsg getDefaultInstanceForType() {
        return com.thoughtworks.message.MessageProtos.CtrlMsg.getDefaultInstance();
      }

      public com.thoughtworks.message.MessageProtos.CtrlMsg build() {
        com.thoughtworks.message.MessageProtos.CtrlMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.thoughtworks.message.MessageProtos.CtrlMsg buildPartial() {
        com.thoughtworks.message.MessageProtos.CtrlMsg result = new com.thoughtworks.message.MessageProtos.CtrlMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.fOName_ = fOName_;
        result.statistics_ = internalGetStatistics();
        result.statistics_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thoughtworks.message.MessageProtos.CtrlMsg) {
          return mergeFrom((com.thoughtworks.message.MessageProtos.CtrlMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thoughtworks.message.MessageProtos.CtrlMsg other) {
        if (other == com.thoughtworks.message.MessageProtos.CtrlMsg.getDefaultInstance()) return this;
        if (!other.getFOName().isEmpty()) {
          fOName_ = other.fOName_;
          onChanged();
        }
        internalGetMutableStatistics().mergeFrom(
            other.internalGetStatistics());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thoughtworks.message.MessageProtos.CtrlMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thoughtworks.message.MessageProtos.CtrlMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fOName_ = "";
      /**
       * <code>string FOName = 1;</code>
       */
      public java.lang.String getFOName() {
        java.lang.Object ref = fOName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fOName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string FOName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFONameBytes() {
        java.lang.Object ref = fOName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fOName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string FOName = 1;</code>
       */
      public Builder setFOName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fOName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string FOName = 1;</code>
       */
      public Builder clearFOName() {
        
        fOName_ = getDefaultInstance().getFOName();
        onChanged();
        return this;
      }
      /**
       * <code>string FOName = 1;</code>
       */
      public Builder setFONameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fOName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> statistics_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetStatistics() {
        if (statistics_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StatisticsDefaultEntryHolder.defaultEntry);
        }
        return statistics_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableStatistics() {
        onChanged();;
        if (statistics_ == null) {
          statistics_ = com.google.protobuf.MapField.newMapField(
              StatisticsDefaultEntryHolder.defaultEntry);
        }
        if (!statistics_.isMutable()) {
          statistics_ = statistics_.copy();
        }
        return statistics_;
      }

      public int getStatisticsCount() {
        return internalGetStatistics().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */

      public boolean containsStatistics(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetStatistics().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStatisticsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getStatistics() {
        return getStatisticsMap();
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getStatisticsMap() {
        return internalGetStatistics().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */

      public int getStatisticsOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStatistics().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */

      public int getStatisticsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStatistics().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStatistics() {
        internalGetMutableStatistics().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */

      public Builder removeStatistics(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStatistics().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableStatistics() {
        return internalGetMutableStatistics().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */
      public Builder putStatistics(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableStatistics().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; Statistics = 2;</code>
       */

      public Builder putAllStatistics(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableStatistics().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:message.CtrlMsg)
    }

    // @@protoc_insertion_point(class_scope:message.CtrlMsg)
    private static final com.thoughtworks.message.MessageProtos.CtrlMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thoughtworks.message.MessageProtos.CtrlMsg();
    }

    public static com.thoughtworks.message.MessageProtos.CtrlMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CtrlMsg>
        PARSER = new com.google.protobuf.AbstractParser<CtrlMsg>() {
      public CtrlMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CtrlMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CtrlMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CtrlMsg> getParserForType() {
      return PARSER;
    }

    public com.thoughtworks.message.MessageProtos.CtrlMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message.DataMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.message.DataType Type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.message.DataType Type = 1;</code>
     */
    com.thoughtworks.message.MessageProtos.DataType getType();

    /**
     * <code>string Id = 2;</code>
     */
    java.lang.String getId();
    /**
     * <code>string Id = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string Value = 3;</code>
     */
    java.lang.String getValue();
    /**
     * <code>string Value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code message.DataMsg}
   */
  public  static final class DataMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message.DataMsg)
      DataMsgOrBuilder {
    // Use DataMsg.newBuilder() to construct.
    private DataMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataMsg() {
      type_ = 0;
      id_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DataMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thoughtworks.message.MessageProtos.internal_static_message_DataMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thoughtworks.message.MessageProtos.internal_static_message_DataMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thoughtworks.message.MessageProtos.DataMsg.class, com.thoughtworks.message.MessageProtos.DataMsg.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.message.DataType Type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.message.DataType Type = 1;</code>
     */
    public com.thoughtworks.message.MessageProtos.DataType getType() {
      com.thoughtworks.message.MessageProtos.DataType result = com.thoughtworks.message.MessageProtos.DataType.valueOf(type_);
      return result == null ? com.thoughtworks.message.MessageProtos.DataType.UNRECOGNIZED : result;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>string Id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string Id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object value_;
    /**
     * <code>string Value = 3;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string Value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.thoughtworks.message.MessageProtos.DataType.TRADE_DATA.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.thoughtworks.message.MessageProtos.DataType.TRADE_DATA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.thoughtworks.message.MessageProtos.DataMsg)) {
        return super.equals(obj);
      }
      com.thoughtworks.message.MessageProtos.DataMsg other = (com.thoughtworks.message.MessageProtos.DataMsg) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getId()
          .equals(other.getId());
      result = result && getValue()
          .equals(other.getValue());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.thoughtworks.message.MessageProtos.DataMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.thoughtworks.message.MessageProtos.DataMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code message.DataMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message.DataMsg)
        com.thoughtworks.message.MessageProtos.DataMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_DataMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_DataMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thoughtworks.message.MessageProtos.DataMsg.class, com.thoughtworks.message.MessageProtos.DataMsg.Builder.class);
      }

      // Construct using com.thoughtworks.message.MessageProtos.DataMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        id_ = "";

        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thoughtworks.message.MessageProtos.internal_static_message_DataMsg_descriptor;
      }

      public com.thoughtworks.message.MessageProtos.DataMsg getDefaultInstanceForType() {
        return com.thoughtworks.message.MessageProtos.DataMsg.getDefaultInstance();
      }

      public com.thoughtworks.message.MessageProtos.DataMsg build() {
        com.thoughtworks.message.MessageProtos.DataMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.thoughtworks.message.MessageProtos.DataMsg buildPartial() {
        com.thoughtworks.message.MessageProtos.DataMsg result = new com.thoughtworks.message.MessageProtos.DataMsg(this);
        result.type_ = type_;
        result.id_ = id_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thoughtworks.message.MessageProtos.DataMsg) {
          return mergeFrom((com.thoughtworks.message.MessageProtos.DataMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thoughtworks.message.MessageProtos.DataMsg other) {
        if (other == com.thoughtworks.message.MessageProtos.DataMsg.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thoughtworks.message.MessageProtos.DataMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thoughtworks.message.MessageProtos.DataMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.message.DataType Type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.message.DataType Type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.message.DataType Type = 1;</code>
       */
      public com.thoughtworks.message.MessageProtos.DataType getType() {
        com.thoughtworks.message.MessageProtos.DataType result = com.thoughtworks.message.MessageProtos.DataType.valueOf(type_);
        return result == null ? com.thoughtworks.message.MessageProtos.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.message.DataType Type = 1;</code>
       */
      public Builder setType(com.thoughtworks.message.MessageProtos.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.message.DataType Type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string Id = 2;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Id = 2;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Id = 2;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string Id = 2;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string Value = 3;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string Value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string Value = 3;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string Value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string Value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:message.DataMsg)
    }

    // @@protoc_insertion_point(class_scope:message.DataMsg)
    private static final com.thoughtworks.message.MessageProtos.DataMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.thoughtworks.message.MessageProtos.DataMsg();
    }

    public static com.thoughtworks.message.MessageProtos.DataMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataMsg>
        PARSER = new com.google.protobuf.AbstractParser<DataMsg>() {
      public DataMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataMsg> getParserForType() {
      return PARSER;
    }

    public com.thoughtworks.message.MessageProtos.DataMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_MsgId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_MsgId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_CtrlMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_CtrlMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_CtrlMsg_StatisticsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_CtrlMsg_StatisticsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_DataMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_DataMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034src/main/proto/message.proto\022\007message\"" +
      "$\n\005MsgId\022\r\n\005ReqId\030\001 \001(\t\022\014\n\004FOId\030\002 \001(\t\"\202\001" +
      "\n\007CtrlMsg\022\016\n\006FOName\030\001 \001(\t\0224\n\nStatistics\030" +
      "\002 \003(\0132 .message.CtrlMsg.StatisticsEntry\032" +
      "1\n\017StatisticsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\005:\0028\001\"E\n\007DataMsg\022\037\n\004Type\030\001 \001(\0162\021.me" +
      "ssage.DataType\022\n\n\002Id\030\002 \001(\t\022\r\n\005Value\030\003 \001(" +
      "\t*+\n\010DataType\022\016\n\nTRADE_DATA\020\000\022\017\n\013MARKET_" +
      "DATA\020\001B)\n\030com.thoughtworks.messageB\rMess" +
      "ageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_message_MsgId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_MsgId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_MsgId_descriptor,
        new java.lang.String[] { "ReqId", "FOId", });
    internal_static_message_CtrlMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_message_CtrlMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_CtrlMsg_descriptor,
        new java.lang.String[] { "FOName", "Statistics", });
    internal_static_message_CtrlMsg_StatisticsEntry_descriptor =
      internal_static_message_CtrlMsg_descriptor.getNestedTypes().get(0);
    internal_static_message_CtrlMsg_StatisticsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_CtrlMsg_StatisticsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_message_DataMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_message_DataMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_DataMsg_descriptor,
        new java.lang.String[] { "Type", "Id", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
